export const ROUTES = {
  admin: {
    login: "/admin/login",
    signup: "/admin/signup",
    forgotPassword: "/admin/forgot-password",
    resetPassword: "/admin/reset-password",
    verifyEmail: "/admin/verify-email",
    twoFA: "/admin/2fa",
    dashboard: "/admin/dashboard",
    employees: "/admin/employees",
    employeeAdd: "/admin/employees/add",
    employeeDetail: (id: string) => `/admin/employees/${id}`,
    companies: "/admin/companies",
    companyAdd: "/admin/companies/add",
    companyDetail: (id: string) => `/admin/companies/${id}`,
    accounts: "/admin/accounts",
    accountDetail: (id: string) => `/admin/accounts/${id}`,
    transactions: "/admin/transactions",
    transactionDetail: (id: string) => `/admin/transactions/${id}`,
    wallet: "/admin/wallet",
    adminWallet: "/admin/admin-wallet",
    cryptoTransactions: "/admin/crypto-transactions",
    activityLogs: "/admin/activity-logs",
    clientActivityLogs: "/admin/client-activity-logs",
    administrators: "/admin/administrators",
    settings: "/admin/settings",
  },
  employer: {
    login: "/user/login",
    signup: "/user/signup",
    forgotPassword: "/user/forgot-password",
    resetPassword: "/user/reset-password",
    verifyEmail: "/user/verify-email",
    twoFA: "/user/2fa",
    dashboard: "/user/dashboard",
    people: "/user/people",
    peopleAdd: "/user/people/add",
    personDetail: (id: string) => `/user/people/${id}`,
    payroll: "/user/payroll",
    payrollCreate: "/user/payroll/create",
    payments: "/user/payments",
    bulkPayouts: "/user/bulk-payouts",
    transfers: "/user/transfers",
    reports: "/user/reports",
    settings: "/user/settings",
  },
  employee: {
    login: "/employee/login",
    signup: "/employee/signup",
    forgotPassword: "/employee/forgot-password",
    resetPassword: "/employee/reset-password",
    verifyEmail: "/employee/verify-email",
    twoFA: "/employee/2fa",
    dashboard: "/employee/dashboard",
    leave: "/employee/leave",
    leaveApply: "/employee/leave/apply",
    leaveCalendar: "/employee/leave/calendar",
    reports: "/employee/reports",
    settings: "/employee/settings",
  },
};
