export const ROUTES = {
  admin: {
    login: "/admin/login",
    signup: "/admin/signup",
    forgotPassword: "/admin/forgot-password",
    resetPassword: "/admin/reset-password",
    verifyEmail: "/admin/verify-email",
    twoFA: "/admin/2fa",
    dashboard: "/admin/dashboard",
    employees: "/admin/employees",
    employeeAdd: "/admin/employees/add",
    employeeDetail: (id: string) => `/admin/employees/${id}`,
    companies: "/admin/companies",
    companyAdd: "/admin/companies/add",
    companyDetail: (id: string) => `/admin/companies/${id}`,
    accounts: "/admin/accounts",
    accountDetail: (id: string) => `/admin/accounts/${id}`,
    transactions: "/admin/transactions",
    transactionDetail: (id: string) => `/admin/transactions/${id}`,
    wallet: "/admin/wallet",
    adminWallet: "/admin/admin-wallet",
    cryptoTransactions: "/admin/crypto-transactions",
    activityLogs: "/admin/activity-logs",
    clientActivityLogs: "/admin/client-activity-logs",
    administrators: "/admin/administrators",
    settings: "/admin/settings",
  },
};
